-- Query the INFORMATION_SCHEMA to get the description of the 'books' table
SELECT 
 COLUMN_NAME, 
 DATA_TYPE,
 CHARACTER_MAXIMUM_LENGTH, 
 IS_NULLABLE, 
 COLUMN_KEY, 
 COLUMN_DEFAULT, 
 EXTRA

FROM 
 INFORMATION_SCHEMA.COLUMNS

WHERE TABLE_NAME = 'Books' AND TABLE_SCHEMA = DATABASE();
